### PR TITLE
Added auth which handles course and course/* structure

### PR DESCRIPTION
**Pull request by songexile**
Handles auth with middleware.js.

### CODE REVIEW

**Comment by songexile** [comment]
Dont merge yet, its broken

**Comment by AwesomeJackify** [comment]
Dw

**Review by AwesomeJackify — CHANGES_REQUESTED** [review]
todo: feature/courses
- remove console logs
- fix navbar not showing in course
- add loader to video
- move course.astro to be index.astro in course/
- fix alert
- remember me
- Forgot your password

**Comment by songexile** [comment]
All changes requested have been made.

**Pull request closed without merging**
